<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>datamaster-common</artifactId>
        <groupId>com.datamaster</groupId>
        <version>${dataMaster.version}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>datamaster-common-category</artifactId>
    <description>
        datamaster-common-category 分类管理核心
    </description>
    <dependencies>
        <dependency>
            <groupId>com.datamaster</groupId>
            <artifactId>datamaster-common-mybatis</artifactId>
            <version>${dataMaster.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>1.5.5.Final</version>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct-jdk8</artifactId>
            <version>1.5.5.Final</version>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct-processor</artifactId>
            <version>1.5.5.Final</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
