CREATE TABLE IF NOT EXISTS COL_ETL_TASK_OPS_POLICY (
    ID BIGINT PRIMARY KEY,
    TASK_ID BIGINT NOT NULL,
    TASK_TYPE VARCHAR(32),
    FAIL_STOP_ENABLED BOOLEAN DEFAULT FALSE,
    AI_MANAGED BOOLEAN DEFAULT FALSE,
    AUTO_RECOVER_ENABLED BOOLEAN DEFAULT FALSE,
    MAX_RECOVER_TIMES INTEGER DEFAULT 1,
    RECOVER_STRATEGY VARCHAR(64) DEFAULT 'SAFE_AUTO',
    NOTIFY_USERS VARCHAR(500),
    VALID_FLAG BOOLEAN DEFAULT TRUE,
    DEL_FLAG BOOLEAN DEFAULT FALSE,
    CREATOR_ID BIGINT,
    CREATE_BY VARCHAR(64),
    CREATE_TIME TIMESTAMP,
    UPDATER_ID BIGINT,
    UPDATE_BY VARCHAR(64),
    UPDATE_TIME TIMESTAMP,
    REMARK VARCHAR(500)
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_COL_ETL_TASK_OPS_POLICY_TASK ON COL_ETL_TASK_OPS_POLICY (TASK_ID);

CREATE TABLE IF NOT EXISTS COL_ETL_TASK_OPS_EVENT (
    ID BIGINT PRIMARY KEY,
    TASK_ID BIGINT NOT NULL,
    TASK_CODE VARCHAR(128),
    TASK_TYPE VARCHAR(32),
    TASK_INSTANCE_ID BIGINT,
    DS_PROCESS_INSTANCE_ID BIGINT,
    INSTANCE_STATUS VARCHAR(32),
    EVENT_TYPE VARCHAR(64),
    FAILURE_TYPE VARCHAR(64),
    RISK_LEVEL VARCHAR(32),
    RECOVERABLE BOOLEAN DEFAULT FALSE,
    ACTION VARCHAR(64),
    ACTION_STATUS VARCHAR(32),
    REASON TEXT,
    SUGGESTION TEXT,
    LOG_EXCERPT TEXT,
    AI_RAW_RESULT TEXT,
    VALID_FLAG BOOLEAN DEFAULT TRUE,
    DEL_FLAG BOOLEAN DEFAULT FALSE,
    CREATOR_ID BIGINT,
    CREATE_BY VARCHAR(64),
    CREATE_TIME TIMESTAMP,
    UPDATER_ID BIGINT,
    UPDATE_BY VARCHAR(64),
    UPDATE_TIME TIMESTAMP,
    REMARK VARCHAR(500)
);

CREATE INDEX IF NOT EXISTS IDX_COL_ETL_TASK_OPS_EVENT_TASK ON COL_ETL_TASK_OPS_EVENT (TASK_ID, CREATE_TIME);
CREATE INDEX IF NOT EXISTS IDX_COL_ETL_TASK_OPS_EVENT_INSTANCE ON COL_ETL_TASK_OPS_EVENT (TASK_INSTANCE_ID);

