CREATE TABLE IF NOT EXISTS AI_SKILL (
    ID BIGINT PRIMARY KEY,
    SKILL_CODE VARCHAR(128) NOT NULL,
    SKILL_NAME VARCHAR(255) NOT NULL,
    SKILL_TYPE VARCHAR(64) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    SOURCE_TYPE VARCHAR(32) NOT NULL,
    BIZ_OBJECT_TYPE VARCHAR(64),
    BIZ_OBJECT_ID BIGINT,
    CONTENT TEXT NOT NULL,
    CONTENT_HASH VARCHAR(128),
    VERSION INTEGER DEFAULT 1,
    DBGPT_SPACE_NAME VARCHAR(128),
    DBGPT_DOCUMENT_NAME VARCHAR(255),
    DBGPT_SYNC_STATUS VARCHAR(32),
    DBGPT_SYNC_MESSAGE VARCHAR(1000),
    CREATOR_ID BIGINT,
    CREATE_BY VARCHAR(64),
    CREATE_TIME TIMESTAMP,
    UPDATER_ID BIGINT,
    UPDATE_BY VARCHAR(64),
    UPDATE_TIME TIMESTAMP,
    REMARK VARCHAR(500),
    DEL_FLAG BOOLEAN DEFAULT FALSE
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_AI_SKILL_CODE ON AI_SKILL (SKILL_CODE);
CREATE INDEX IF NOT EXISTS IDX_AI_SKILL_TYPE_STATUS ON AI_SKILL (SKILL_TYPE, STATUS);
CREATE INDEX IF NOT EXISTS IDX_AI_SKILL_BIZ_OBJECT ON AI_SKILL (BIZ_OBJECT_TYPE, BIZ_OBJECT_ID);
ALTER TABLE AI_SKILL ADD COLUMN IF NOT EXISTS DBGPT_SPACE_NAME VARCHAR(128);
ALTER TABLE AI_SKILL ADD COLUMN IF NOT EXISTS DBGPT_DOCUMENT_NAME VARCHAR(255);
ALTER TABLE AI_SKILL ADD COLUMN IF NOT EXISTS DBGPT_SYNC_STATUS VARCHAR(32);
ALTER TABLE AI_SKILL ADD COLUMN IF NOT EXISTS DBGPT_SYNC_MESSAGE VARCHAR(1000);

CREATE TABLE IF NOT EXISTS AI_SKILL_VERSION (
    ID BIGINT PRIMARY KEY,
    SKILL_ID BIGINT NOT NULL,
    VERSION INTEGER NOT NULL,
    CONTENT TEXT NOT NULL,
    CHANGE_TYPE VARCHAR(32),
    CHANGE_REMARK VARCHAR(500),
    CREATOR_ID BIGINT,
    CREATE_BY VARCHAR(64),
    CREATE_TIME TIMESTAMP,
    UPDATER_ID BIGINT,
    UPDATE_BY VARCHAR(64),
    UPDATE_TIME TIMESTAMP,
    REMARK VARCHAR(500)
);

CREATE INDEX IF NOT EXISTS IDX_AI_SKILL_VERSION_SKILL ON AI_SKILL_VERSION (SKILL_ID, VERSION);

CREATE TABLE IF NOT EXISTS AI_SKILL_REF (
    ID BIGINT PRIMARY KEY,
    SKILL_ID BIGINT NOT NULL,
    REF_TYPE VARCHAR(64) NOT NULL,
    REF_ID BIGINT,
    REF_CODE VARCHAR(255),
    REF_NAME VARCHAR(255),
    CREATOR_ID BIGINT,
    CREATE_BY VARCHAR(64),
    CREATE_TIME TIMESTAMP,
    UPDATER_ID BIGINT,
    UPDATE_BY VARCHAR(64),
    UPDATE_TIME TIMESTAMP,
    REMARK VARCHAR(500)
);

CREATE INDEX IF NOT EXISTS IDX_AI_SKILL_REF_SKILL ON AI_SKILL_REF (SKILL_ID);
CREATE INDEX IF NOT EXISTS IDX_AI_SKILL_REF_OBJECT ON AI_SKILL_REF (REF_TYPE, REF_ID);

CREATE TABLE IF NOT EXISTS AI_SKILL_REPORT_TEMPLATE (
    ID BIGINT PRIMARY KEY,
    SKILL_ID BIGINT NOT NULL,
    TEMPLATE_CODE VARCHAR(128) NOT NULL,
    TEMPLATE_NAME VARCHAR(255) NOT NULL,
    TEMPLATE_CONTENT TEXT NOT NULL,
    STATUS VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    DEFAULT_FLAG BOOLEAN DEFAULT FALSE,
    VERSION INTEGER DEFAULT 1,
    CREATOR_ID BIGINT,
    CREATE_BY VARCHAR(64),
    CREATE_TIME TIMESTAMP,
    UPDATER_ID BIGINT,
    UPDATE_BY VARCHAR(64),
    UPDATE_TIME TIMESTAMP,
    REMARK VARCHAR(500),
    DEL_FLAG BOOLEAN DEFAULT FALSE
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_AI_SKILL_REPORT_TEMPLATE_CODE ON AI_SKILL_REPORT_TEMPLATE (SKILL_ID, TEMPLATE_CODE, DEL_FLAG);
CREATE INDEX IF NOT EXISTS IDX_AI_SKILL_REPORT_TEMPLATE_SKILL ON AI_SKILL_REPORT_TEMPLATE (SKILL_ID, DEFAULT_FLAG, STATUS);

CREATE TABLE IF NOT EXISTS AI_ASK_SESSION (
    ID BIGINT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    PROJECT_ID BIGINT,
    PROJECT_CODE VARCHAR(128),
    TITLE VARCHAR(255) NOT NULL,
    MODE VARCHAR(32) DEFAULT 'qa',
    DATASOURCE_ID BIGINT,
    DATASOURCE_NAME VARCHAR(255),
    SKILL_ID BIGINT,
    TEMPLATE_ID BIGINT,
    RETURN_SQL BOOLEAN DEFAULT FALSE,
    MESSAGE_COUNT INTEGER DEFAULT 0,
    CREATOR_ID BIGINT,
    CREATE_BY VARCHAR(64),
    CREATE_TIME TIMESTAMP,
    UPDATER_ID BIGINT,
    UPDATE_BY VARCHAR(64),
    UPDATE_TIME TIMESTAMP,
    REMARK VARCHAR(500),
    DEL_FLAG BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS IDX_AI_ASK_SESSION_SCOPE ON AI_ASK_SESSION (USER_ID, PROJECT_ID, UPDATE_TIME DESC);

CREATE TABLE IF NOT EXISTS AI_ASK_MESSAGE (
    ID BIGINT PRIMARY KEY,
    SESSION_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    PROJECT_ID BIGINT,
    ROLE VARCHAR(32) NOT NULL,
    CONTENT TEXT,
    DISPLAY_CONTENT TEXT,
    PAYLOAD_JSON TEXT,
    CREATOR_ID BIGINT,
    CREATE_BY VARCHAR(64),
    CREATE_TIME TIMESTAMP,
    UPDATER_ID BIGINT,
    UPDATE_BY VARCHAR(64),
    UPDATE_TIME TIMESTAMP,
    REMARK VARCHAR(500),
    DEL_FLAG BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS IDX_AI_ASK_MESSAGE_SESSION ON AI_ASK_MESSAGE (SESSION_ID, ID);

ALTER TABLE AST_DATASOURCE ADD COLUMN IF NOT EXISTS DBGPT_DATASOURCE_ID INTEGER;
ALTER TABLE AST_DATASOURCE ADD COLUMN IF NOT EXISTS DBGPT_SYNC_STATUS VARCHAR(32);
ALTER TABLE AST_DATASOURCE ADD COLUMN IF NOT EXISTS DBGPT_SYNC_MESSAGE VARCHAR(1000);

CREATE TABLE IF NOT EXISTS COL_ETL_TASK_OPS_POLICY (
    ID BIGINT PRIMARY KEY,
    TASK_ID BIGINT NOT NULL,
    TASK_TYPE VARCHAR(32),
    FAIL_STOP_ENABLED BOOLEAN DEFAULT FALSE,
    AI_MANAGED BOOLEAN DEFAULT FALSE,
    AUTO_RECOVER_ENABLED BOOLEAN DEFAULT FALSE,
    MAX_RECOVER_TIMES INTEGER DEFAULT 1,
    RECOVER_STRATEGY VARCHAR(64) DEFAULT 'SAFE_AUTO',
    NOTIFY_USERS VARCHAR(500),
    VALID_FLAG BOOLEAN DEFAULT TRUE,
    DEL_FLAG BOOLEAN DEFAULT FALSE,
    CREATOR_ID BIGINT,
    CREATE_BY VARCHAR(64),
    CREATE_TIME TIMESTAMP,
    UPDATER_ID BIGINT,
    UPDATE_BY VARCHAR(64),
    UPDATE_TIME TIMESTAMP,
    REMARK VARCHAR(500)
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_COL_ETL_TASK_OPS_POLICY_TASK ON COL_ETL_TASK_OPS_POLICY (TASK_ID);

CREATE TABLE IF NOT EXISTS COL_ETL_TASK_OPS_EVENT (
    ID BIGINT PRIMARY KEY,
    TASK_ID BIGINT NOT NULL,
    TASK_CODE VARCHAR(128),
    TASK_TYPE VARCHAR(32),
    TASK_INSTANCE_ID BIGINT,
    DS_PROCESS_INSTANCE_ID BIGINT,
    INSTANCE_STATUS VARCHAR(32),
    EVENT_TYPE VARCHAR(64),
    FAILURE_TYPE VARCHAR(64),
    RISK_LEVEL VARCHAR(32),
    RECOVERABLE BOOLEAN DEFAULT FALSE,
    ACTION VARCHAR(64),
    ACTION_STATUS VARCHAR(32),
    REASON TEXT,
    SUGGESTION TEXT,
    LOG_EXCERPT TEXT,
    AI_RAW_RESULT TEXT,
    VALID_FLAG BOOLEAN DEFAULT TRUE,
    DEL_FLAG BOOLEAN DEFAULT FALSE,
    CREATOR_ID BIGINT,
    CREATE_BY VARCHAR(64),
    CREATE_TIME TIMESTAMP,
    UPDATER_ID BIGINT,
    UPDATE_BY VARCHAR(64),
    UPDATE_TIME TIMESTAMP,
    REMARK VARCHAR(500)
);

CREATE INDEX IF NOT EXISTS IDX_COL_ETL_TASK_OPS_EVENT_TASK ON COL_ETL_TASK_OPS_EVENT (TASK_ID, CREATE_TIME);
CREATE INDEX IF NOT EXISTS IDX_COL_ETL_TASK_OPS_EVENT_INSTANCE ON COL_ETL_TASK_OPS_EVENT (TASK_INSTANCE_ID);

INSERT INTO SYSTEM_MENU (
    MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
    IS_FRAME, IS_CACHE, ROUTE_NAME, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON,
    CREATE_BY, CREATE_TIME, REMARK
)
SELECT
    2733, '智能问数', 0, 6, 'ai', NULL, NULL,
    1, 0, NULL, 'M', '0', '0', NULL, 'znfx',
    'admin', NOW(), NULL
WHERE NOT EXISTS (
    SELECT 1 FROM SYSTEM_MENU WHERE MENU_ID = 2733
);

UPDATE SYSTEM_MENU
SET MENU_NAME = '智能问数',
    PARENT_ID = 0,
    ORDER_NUM = 6,
    PATH = 'ai',
    COMPONENT = NULL,
    QUERY = NULL,
    MENU_TYPE = 'M',
    VISIBLE = '0',
    STATUS = '0',
    PERMS = NULL,
    ICON = 'znfx'
WHERE MENU_ID = 2733;

UPDATE SYSTEM_MENU
SET VISIBLE = '1',
    STATUS = '1',
    REMARK = COALESCE(REMARK, '') || CASE WHEN COALESCE(REMARK, '') = '' THEN '' ELSE '; ' END || '旧AI模型管理模块未随主服务部署，默认隐藏'
WHERE COMPONENT = 'ai/model/index';

INSERT INTO SYSTEM_MENU (
    MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
    IS_FRAME, IS_CACHE, ROUTE_NAME, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON,
    CREATE_BY, CREATE_TIME, REMARK
)
SELECT
    2751, '问数', 2733, 1, 'ask', 'ai/chat/index/index', NULL,
    1, 0, NULL, 'C', '0', '0', 'ai:ask-data:query', 'message',
    'admin', NOW(), NULL
WHERE NOT EXISTS (
    SELECT 1 FROM SYSTEM_MENU WHERE COMPONENT = 'ai/chat/index/index'
);

UPDATE SYSTEM_MENU
SET MENU_NAME = '问数',
    PARENT_ID = 2733,
    ORDER_NUM = 1,
    PATH = 'ask',
    COMPONENT = 'ai/chat/index/index',
    QUERY = NULL,
    MENU_TYPE = 'C',
    VISIBLE = '0',
    STATUS = '0',
    PERMS = 'ai:ask-data:query',
    ICON = 'message'
WHERE COMPONENT = 'ai/chat/index/index';

INSERT INTO SYSTEM_MENU (
    MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
    IS_FRAME, IS_CACHE, ROUTE_NAME, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON,
    CREATE_BY, CREATE_TIME, REMARK
)
SELECT
    2750, 'Skill管理', 2733, 2, 'skill', 'ai/skill/index', NULL,
    1, 0, NULL, 'C', '0', '0', 'ai:skill:list', 'skill',
    'admin', NOW(), NULL
WHERE NOT EXISTS (
    SELECT 1 FROM SYSTEM_MENU WHERE COMPONENT = 'ai/skill/index'
);

UPDATE SYSTEM_MENU
SET MENU_NAME = 'Skill管理',
    PARENT_ID = 2733,
    ORDER_NUM = 2,
    PATH = 'skill',
    COMPONENT = 'ai/skill/index',
    QUERY = NULL,
    MENU_TYPE = 'C',
    VISIBLE = '0',
    STATUS = '0',
    PERMS = 'ai:skill:list',
    ICON = 'skill'
WHERE COMPONENT = 'ai/skill/index';

INSERT INTO SYSTEM_MENU (
    MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
    IS_FRAME, IS_CACHE, ROUTE_NAME, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON,
    CREATE_BY, CREATE_TIME, REMARK
)
SELECT *
FROM (VALUES
    (2752, 'Skill查询', 2750, 1, '#', NULL, NULL, 1, 0, NULL, 'F', '0', '0', 'ai:skill:query', '#', 'admin', NOW(), NULL),
    (2753, 'Skill新增', 2750, 2, '#', NULL, NULL, 1, 0, NULL, 'F', '0', '0', 'ai:skill:add', '#', 'admin', NOW(), NULL),
    (2754, 'Skill修改', 2750, 3, '#', NULL, NULL, 1, 0, NULL, 'F', '0', '0', 'ai:skill:edit', '#', 'admin', NOW(), NULL),
    (2755, 'Skill删除', 2750, 4, '#', NULL, NULL, 1, 0, NULL, 'F', '0', '0', 'ai:skill:remove', '#', 'admin', NOW(), NULL),
    (2756, 'Skill发布', 2750, 5, '#', NULL, NULL, 1, 0, NULL, 'F', '0', '0', 'ai:skill:publish', '#', 'admin', NOW(), NULL),
    (2757, 'Skill生成', 2750, 6, '#', NULL, NULL, 1, 0, NULL, 'F', '0', '0', 'ai:skill:generate', '#', 'admin', NOW(), NULL),
    (2758, 'Skill同步', 2750, 7, '#', NULL, NULL, 1, 0, NULL, 'F', '0', '0', 'ai:skill:sync', '#', 'admin', NOW(), NULL)
) AS menu_items (
    MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
    IS_FRAME, IS_CACHE, ROUTE_NAME, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON,
    CREATE_BY, CREATE_TIME, REMARK
)
WHERE NOT EXISTS (
    SELECT 1 FROM SYSTEM_MENU target
    WHERE target.MENU_ID = menu_items.MENU_ID
       OR target.PERMS = menu_items.PERMS
);

UPDATE SYSTEM_MENU
SET PARENT_ID = 2750,
    MENU_TYPE = 'F',
    PATH = '#',
    COMPONENT = NULL,
    QUERY = NULL,
    VISIBLE = '0',
    STATUS = '0',
    ICON = '#'
WHERE PERMS IN (
    'ai:skill:query',
    'ai:skill:add',
    'ai:skill:edit',
    'ai:skill:remove',
    'ai:skill:publish',
    'ai:skill:generate',
    'ai:skill:sync'
);

INSERT INTO SYSTEM_ROLE_MENU (ROLE_ID, MENU_ID, PROJECT_ID)
SELECT ROLE_ID, 2733, COALESCE(PROJECT_ID, 0)
FROM SYSTEM_ROLE_MENU role_menu_source
WHERE role_menu_source.MENU_ID IN (2724, 2733)
  AND NOT EXISTS (
    SELECT 1 FROM SYSTEM_ROLE_MENU target
    WHERE target.ROLE_ID = role_menu_source.ROLE_ID
      AND target.MENU_ID = 2733
      AND COALESCE(target.PROJECT_ID, -1) = COALESCE(role_menu_source.PROJECT_ID, 0)
);

INSERT INTO SYSTEM_ROLE_MENU (ROLE_ID, MENU_ID, PROJECT_ID)
SELECT ROLE_ID, 2751, COALESCE(PROJECT_ID, 0)
FROM SYSTEM_ROLE_MENU role_menu_source
WHERE role_menu_source.MENU_ID IN (2724, 2733)
  AND NOT EXISTS (
    SELECT 1 FROM SYSTEM_ROLE_MENU target
    WHERE target.ROLE_ID = role_menu_source.ROLE_ID
      AND target.MENU_ID = 2751
      AND COALESCE(target.PROJECT_ID, -1) = COALESCE(role_menu_source.PROJECT_ID, 0)
);

INSERT INTO SYSTEM_ROLE_MENU (ROLE_ID, MENU_ID, PROJECT_ID)
SELECT ROLE_ID, 2750, COALESCE(PROJECT_ID, 0)
FROM SYSTEM_ROLE_MENU role_menu_source
WHERE role_menu_source.MENU_ID IN (2724, 2733)
  AND NOT EXISTS (
    SELECT 1 FROM SYSTEM_ROLE_MENU target
    WHERE target.ROLE_ID = role_menu_source.ROLE_ID
      AND target.MENU_ID = 2750
      AND COALESCE(target.PROJECT_ID, -1) = COALESCE(role_menu_source.PROJECT_ID, 0)
);

INSERT INTO SYSTEM_ROLE_MENU (ROLE_ID, MENU_ID, PROJECT_ID)
SELECT role_menu_source.ROLE_ID, menu.MENU_ID, COALESCE(role_menu_source.PROJECT_ID, 0)
FROM SYSTEM_ROLE_MENU role_menu_source
JOIN SYSTEM_MENU menu ON menu.PERMS IN (
    'ai:skill:query',
    'ai:skill:add',
    'ai:skill:edit',
    'ai:skill:remove',
    'ai:skill:publish',
    'ai:skill:generate',
    'ai:skill:sync'
)
WHERE role_menu_source.MENU_ID IN (2724, 2733, 2750, 2751)
  AND NOT EXISTS (
    SELECT 1 FROM SYSTEM_ROLE_MENU target
    WHERE target.ROLE_ID = role_menu_source.ROLE_ID
      AND target.MENU_ID = menu.MENU_ID
      AND COALESCE(target.PROJECT_ID, -1) = COALESCE(role_menu_source.PROJECT_ID, 0)
);

UPDATE AI_SKILL
SET STATUS = 'ARCHIVED',
    REMARK = COALESCE(REMARK, '') || CASE WHEN COALESCE(REMARK, '') = '' THEN '' ELSE '; ' END || '平台级Skill已改为内置资源'
WHERE SKILL_TYPE IN ('PLATFORM_METADATA', 'PLATFORM_QUALITY')
  AND STATUS <> 'ARCHIVED';

INSERT INTO SYSTEM_MENU (
    MENU_ID, MENU_NAME, PARENT_ID, ORDER_NUM, PATH, COMPONENT, QUERY,
    IS_FRAME, IS_CACHE, ROUTE_NAME, MENU_TYPE, VISIBLE, STATUS, PERMS, ICON,
    CREATE_BY, CREATE_TIME, REMARK
)
SELECT
    2760, 'AI运维', 2, 6, 'ai-ops', 'sys/monitor/aiOps/index', NULL,
    1, 0, NULL, 'C', '0', '0', 'monitor:aiops:list', 'znfx',
    'admin', NOW(), 'AI运维诊断菜单'
WHERE NOT EXISTS (
    SELECT 1 FROM SYSTEM_MENU WHERE MENU_ID = 2760 OR COMPONENT = 'sys/monitor/aiOps/index'
);

UPDATE SYSTEM_MENU
SET MENU_NAME = 'AI运维',
    PARENT_ID = 2,
    ORDER_NUM = 6,
    PATH = 'ai-ops',
    COMPONENT = 'sys/monitor/aiOps/index',
    QUERY = NULL,
    MENU_TYPE = 'C',
    VISIBLE = '0',
    STATUS = '0',
    PERMS = 'monitor:aiops:list',
    ICON = 'znfx'
WHERE MENU_ID = 2760 OR COMPONENT = 'sys/monitor/aiOps/index';

INSERT INTO SYSTEM_ROLE_MENU (ROLE_ID, MENU_ID, PROJECT_ID)
SELECT role_menu_source.ROLE_ID, menu.MENU_ID, COALESCE(role_menu_source.PROJECT_ID, 0)
FROM SYSTEM_ROLE_MENU role_menu_source
JOIN SYSTEM_MENU menu ON menu.COMPONENT = 'sys/monitor/aiOps/index'
WHERE role_menu_source.MENU_ID IN (2, 112)
  AND NOT EXISTS (
    SELECT 1 FROM SYSTEM_ROLE_MENU target
    WHERE target.ROLE_ID = role_menu_source.ROLE_ID
      AND target.MENU_ID = menu.MENU_ID
      AND COALESCE(target.PROJECT_ID, -1) = COALESCE(role_menu_source.PROJECT_ID, 0)
);
