<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>datamaster-metadata</artifactId>
        <groupId>com.datamaster</groupId>
        <version>${dataMaster.version}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>datamaster-metadata-core</artifactId>
    <description>
        datamaster-metadata-core 元数据采集与质量探查核心模块
    </description>
    <dependencies>
        <dependency>
            <groupId>com.datamaster</groupId>
            <artifactId>datamaster-metadata-interface</artifactId>
            <version>${dataMaster.version}</version>
        </dependency>
        <dependency>
            <groupId>com.datamaster</groupId>
            <artifactId>datamaster-common-config</artifactId>
            <version>${dataMaster.version}</version>
        </dependency>
        <dependency>
            <groupId>com.datamaster</groupId>
            <artifactId>datamaster-common-base</artifactId>
            <version>${dataMaster.version}</version>
        </dependency>
        <dependency>
            <groupId>com.datamaster</groupId>
            <artifactId>datamaster-common-websocket</artifactId>
            <version>${dataMaster.version}</version>
        </dependency>
        <dependency>
            <groupId>com.datamaster</groupId>
            <artifactId>datamaster-common-datasource</artifactId>
            <version>${dataMaster.version}</version>
        </dependency>
        <dependency>
            <groupId>com.datamaster</groupId>
            <artifactId>datamaster-common-mybatis</artifactId>
            <version>${dataMaster.version}</version>
        </dependency>
        <dependency>
            <groupId>com.datamaster</groupId>
            <artifactId>datamaster-common-common</artifactId>
            <exclusions>
                <exclusion>
                    <artifactId>kafka-clients</artifactId>
                    <groupId>org.apache.kafka</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.datamaster</groupId>
            <artifactId>datamaster-common-datasource-mgmt</artifactId>
        </dependency>
        <dependency>
            <groupId>com.datamaster</groupId>
            <artifactId>datamaster-api-ds</artifactId>
            <version>${dataMaster.version}</version>
        </dependency>
        <dependency>
            <groupId>com.datamaster</groupId>
            <artifactId>datamaster-assets-interface</artifactId>
            <version>${dataMaster.version}</version>
        </dependency>
        <dependency>
            <groupId>com.datamaster</groupId>
            <artifactId>datamaster-system</artifactId>
            <version>${dataMaster.version}</version>
        </dependency>
        <dependency>
            <groupId>com.datamaster</groupId>
            <artifactId>datamaster-collector-interface</artifactId>
            <version>${dataMaster.version}</version>
        </dependency>
        <dependency>
            <groupId>com.datamaster</groupId>
            <artifactId>datamaster-governance-interface</artifactId>
            <version>${dataMaster.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-common</artifactId>
            <version>${hadoop.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>slf4j-reload4j</artifactId>
                    <groupId>org.slf4j</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
