-- =============================================
-- 本体模型模块 ONT_ 表结构 (PostgreSQL)
-- 执行前请备份数据库
-- 注意: 必须用应用连接账号执行 (dev 为 datamaster),
--       否则表 owner 错误会导致应用报 permission denied
-- 本文件为 UTF-8 编码, 执行前必须保证客户端按 UTF-8 读取:
--   psql    : 先执行 \encoding UTF8 (或 PGCLIENTENCODING=UTF8)
--             切勿用 PowerShell Get-Content 管道灌入(会按 GBK 误读导致中文注释乱码)
--   Navicat: 查询窗口编码选择 65001 (UTF-8)
-- =============================================
SET client_encoding = 'UTF8';

-- 1. 本体
CREATE TABLE IF NOT EXISTS ONT_ONTOLOGY (
    ID              BIGINT       PRIMARY KEY,
    NAME            VARCHAR(100) NOT NULL,
    CODE            VARCHAR(100) NOT NULL,
    DESCRIPTION     TEXT,
    SPACE_ID        BIGINT,
    SPACE_CODE      VARCHAR(50),
    STATUS          SMALLINT     DEFAULT 0,
    CREATOR_ID      BIGINT,
    CREATE_BY       VARCHAR(50),
    CREATE_TIME     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATER_ID      BIGINT,
    UPDATE_BY       VARCHAR(50),
    UPDATE_TIME     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    DEL_FLAG        SMALLINT     DEFAULT 0
);
COMMENT ON TABLE ONT_ONTOLOGY IS '本体';
COMMENT ON COLUMN ONT_ONTOLOGY.STATUS IS '0=草稿 1=已发布 2=已归档';

-- 2. 概念
CREATE TABLE IF NOT EXISTS ONT_CONCEPT (
    ID              BIGINT       PRIMARY KEY,
    ONTOLOGY_ID     BIGINT       NOT NULL,
    NAME            VARCHAR(100) NOT NULL,
    CODE            VARCHAR(100) NOT NULL,
    DESCRIPTION     TEXT,
    ICON            VARCHAR(50),
    COLOR           VARCHAR(20),
    SORT_ORDER      INT          DEFAULT 0,
    STATUS          SMALLINT     DEFAULT 0,
    CREATOR_ID      BIGINT,
    CREATE_BY       VARCHAR(50),
    CREATE_TIME     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATER_ID      BIGINT,
    UPDATE_BY       VARCHAR(50),
    UPDATE_TIME     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    DEL_FLAG        SMALLINT     DEFAULT 0
);
COMMENT ON TABLE ONT_CONCEPT IS '本体概念';
COMMENT ON COLUMN ONT_CONCEPT.STATUS IS '0=草稿 1=已发布';
CREATE INDEX IDX_ONT_CONCEPT_OID ON ONT_CONCEPT(ONTOLOGY_ID);

-- 3. 属性
CREATE TABLE IF NOT EXISTS ONT_PROPERTY (
    ID              BIGINT       PRIMARY KEY,
    CONCEPT_ID      BIGINT       NOT NULL,
    NAME            VARCHAR(100) NOT NULL,
    CODE            VARCHAR(100) NOT NULL,
    DATA_TYPE       VARCHAR(50)  DEFAULT 'string',
    DESCRIPTION     TEXT,
    IS_PRIMARY      BOOLEAN      DEFAULT FALSE,
    IS_REQUIRED     BOOLEAN      DEFAULT FALSE,
    DEFAULT_VALUE   VARCHAR(500),
    SORT_ORDER      INT          DEFAULT 0,
    CREATOR_ID      BIGINT,
    CREATE_BY       VARCHAR(50),
    CREATE_TIME     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATER_ID      BIGINT,
    UPDATE_BY       VARCHAR(50),
    UPDATE_TIME     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    DEL_FLAG        SMALLINT     DEFAULT 0
);
COMMENT ON TABLE ONT_PROPERTY IS '本体属性';
COMMENT ON COLUMN ONT_PROPERTY.DATA_TYPE IS 'string/integer/decimal/date/boolean/text';
CREATE INDEX IDX_ONT_PROP_CID ON ONT_PROPERTY(CONCEPT_ID);

-- 4. 关系
CREATE TABLE IF NOT EXISTS ONT_RELATION (
    ID                   BIGINT       PRIMARY KEY,
    ONTOLOGY_ID          BIGINT       NOT NULL,
    NAME                 VARCHAR(100) NOT NULL,
    CODE                 VARCHAR(100) NOT NULL,
    SOURCE_CONCEPT_ID    BIGINT       NOT NULL,
    TARGET_CONCEPT_ID    BIGINT       NOT NULL,
    RELATION_TYPE        VARCHAR(20)  DEFAULT 'one_to_many',
    DESCRIPTION          TEXT,
    SORT_ORDER           INT          DEFAULT 0,
    CREATOR_ID           BIGINT,
    CREATE_BY            VARCHAR(50),
    CREATE_TIME          TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATER_ID           BIGINT,
    UPDATE_BY            VARCHAR(50),
    UPDATE_TIME          TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    DEL_FLAG             SMALLINT     DEFAULT 0
);
COMMENT ON TABLE ONT_RELATION IS '本体关系';
COMMENT ON COLUMN ONT_RELATION.RELATION_TYPE IS 'one_to_one/one_to_many/many_to_one/many_to_many';
CREATE INDEX IDX_ONT_REL_OID ON ONT_RELATION(ONTOLOGY_ID);

-- 5. 概念表绑定
CREATE TABLE IF NOT EXISTS ONT_CONCEPT_TABLE (
    ID              BIGINT       PRIMARY KEY,
    CONCEPT_ID      BIGINT       NOT NULL,
    DATASOURCE_ID   BIGINT       NOT NULL,
    DATABASE_NAME   VARCHAR(100),
    TABLE_NAME      VARCHAR(100) NOT NULL,
    SCHEMA_NAME     VARCHAR(100),
    CREATOR_ID      BIGINT,
    CREATE_BY       VARCHAR(50),
    CREATE_TIME     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATER_ID      BIGINT,
    UPDATE_BY       VARCHAR(50),
    UPDATE_TIME     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    DEL_FLAG        SMALLINT     DEFAULT 0
);
COMMENT ON TABLE ONT_CONCEPT_TABLE IS '概念表绑定';
CREATE INDEX IDX_ONT_CTABLE_CID ON ONT_CONCEPT_TABLE(CONCEPT_ID);

-- 6. 属性字段绑定
CREATE TABLE IF NOT EXISTS ONT_PROPERTY_COLUMN (
    ID                BIGINT       PRIMARY KEY,
    PROPERTY_ID       BIGINT       NOT NULL,
    CONCEPT_TABLE_ID  BIGINT       NOT NULL,
    COLUMN_NAME       VARCHAR(100) NOT NULL,
    CREATOR_ID        BIGINT,
    CREATE_BY         VARCHAR(50),
    CREATE_TIME       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATER_ID        BIGINT,
    UPDATE_BY         VARCHAR(50),
    UPDATE_TIME       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    DEL_FLAG          SMALLINT     DEFAULT 0
);
COMMENT ON TABLE ONT_PROPERTY_COLUMN IS '属性字段绑定';
CREATE INDEX IDX_ONT_PCOL_PID ON ONT_PROPERTY_COLUMN(PROPERTY_ID);

-- 7. 关系字段绑定
CREATE TABLE IF NOT EXISTS ONT_RELATION_COLUMN (
    ID                      BIGINT       PRIMARY KEY,
    RELATION_ID             BIGINT       NOT NULL,
    SOURCE_CONCEPT_TABLE_ID BIGINT       NOT NULL,
    SOURCE_COLUMN           VARCHAR(100) NOT NULL,
    TARGET_CONCEPT_TABLE_ID BIGINT       NOT NULL,
    TARGET_COLUMN           VARCHAR(100) NOT NULL,
    CREATOR_ID              BIGINT,
    CREATE_BY               VARCHAR(50),
    CREATE_TIME             TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATER_ID              BIGINT,
    UPDATE_BY               VARCHAR(50),
    UPDATE_TIME             TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    DEL_FLAG                SMALLINT     DEFAULT 0
);
COMMENT ON TABLE ONT_RELATION_COLUMN IS '关系字段绑定';
CREATE INDEX IDX_ONT_RCOL_RID ON ONT_RELATION_COLUMN(RELATION_ID);

-- 8. 动作定义
CREATE TABLE IF NOT EXISTS ONT_ACTION (
    ID              BIGINT       PRIMARY KEY,
    ONTOLOGY_ID     BIGINT       NOT NULL,
    NAME            VARCHAR(100) NOT NULL,
    ACTION_TYPE     VARCHAR(20)  NOT NULL,
    CONCEPT_ID      BIGINT       NOT NULL,
    DESCRIPTION     TEXT,
    CREATOR_ID      BIGINT,
    CREATE_BY       VARCHAR(50),
    CREATE_TIME     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATER_ID      BIGINT,
    UPDATE_BY       VARCHAR(50),
    UPDATE_TIME     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    DEL_FLAG        SMALLINT     DEFAULT 0
);
COMMENT ON TABLE ONT_ACTION IS '动作定义';
COMMENT ON COLUMN ONT_ACTION.ACTION_TYPE IS 'CREATE/UPDATE/DELETE/QUERY';
CREATE INDEX IDX_ONT_ACT_OID ON ONT_ACTION(ONTOLOGY_ID);

-- 9. 动作执行记录
CREATE TABLE IF NOT EXISTS ONT_ACTION_EXECUTION (
    ID              BIGINT        PRIMARY KEY,
    ACTION_ID       BIGINT        NOT NULL,
    ONTOLOGY_ID     BIGINT        NOT NULL,
    EXECUTOR_ID     BIGINT,
    SPACE_ID        BIGINT,
    SPACE_CODE      VARCHAR(50),
    INPUT_PARAMS    JSONB,
    GENERATED_SQL   TEXT,
    PREVIEW_RESULT  JSONB,
    BEFORE_DATA     JSONB,
    AFTER_DATA      JSONB,
    STATUS          VARCHAR(20)   DEFAULT 'DRAFT',
    APPROVAL_REASON TEXT,
    APPROVER_ID     BIGINT,
    APPROVE_TIME    TIMESTAMP,
    EXECUTE_TIME    TIMESTAMP,
    ERROR_MESSAGE   TEXT,
    CREATOR_ID      BIGINT,
    CREATE_BY       VARCHAR(50),
    CREATE_TIME     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    UPDATER_ID      BIGINT,
    UPDATE_BY       VARCHAR(50),
    UPDATE_TIME     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    DEL_FLAG        SMALLINT      DEFAULT 0
);
COMMENT ON TABLE ONT_ACTION_EXECUTION IS '动作执行记录';
COMMENT ON COLUMN ONT_ACTION_EXECUTION.STATUS IS 'DRAFT/PENDING_APPROVAL/APPROVED/REJECTED/EXECUTED/FAILED';
CREATE INDEX IDX_ONT_AEXEC_AID ON ONT_ACTION_EXECUTION(ACTION_ID);
CREATE INDEX IDX_ONT_AEXEC_STATUS ON ONT_ACTION_EXECUTION(STATUS);

-- 10. 通知配置
CREATE TABLE IF NOT EXISTS ONT_NOTIFICATION_CONFIG (
    ID              BIGINT       PRIMARY KEY,
    ONTOLOGY_ID     BIGINT       NOT NULL,
    NAME            VARCHAR(100) NOT NULL,
    NOTIFY_TYPE     VARCHAR(20)  NOT NULL,
    TRIGGER_EVENT   VARCHAR(50)  NOT NULL,
    CONFIG          JSONB,
    TEMPLATE        TEXT,
    ENABLED         BOOLEAN      DEFAULT TRUE,
    CREATOR_ID      BIGINT,
    CREATE_BY       VARCHAR(50),
    CREATE_TIME     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATER_ID      BIGINT,
    UPDATE_BY       VARCHAR(50),
    UPDATE_TIME     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    DEL_FLAG        SMALLINT     DEFAULT 0
);
COMMENT ON TABLE ONT_NOTIFICATION_CONFIG IS '通知配置';
COMMENT ON COLUMN ONT_NOTIFICATION_CONFIG.NOTIFY_TYPE IS 'HTTP/EMAIL/DS_WORKFLOW';
COMMENT ON COLUMN ONT_NOTIFICATION_CONFIG.TRIGGER_EVENT IS 'ACTION_EXECUTED/APPROVAL_RESULT/ACTION_FAILED';
CREATE INDEX IDX_ONT_NCFG_OID ON ONT_NOTIFICATION_CONFIG(ONTOLOGY_ID);

-- 11. 通知记录
CREATE TABLE IF NOT EXISTS ONT_NOTIFICATION_LOG (
    ID              BIGINT       PRIMARY KEY,
    CONFIG_ID       BIGINT       NOT NULL,
    EXECUTION_ID    BIGINT,
    STATUS          VARCHAR(20)  DEFAULT 'PENDING',
    RESPONSE        TEXT,
    ERROR_MESSAGE   TEXT,
    SEND_TIME       TIMESTAMP,
    CREATOR_ID      BIGINT,
    CREATE_BY       VARCHAR(50),
    CREATE_TIME     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATER_ID      BIGINT,
    UPDATE_BY       VARCHAR(50),
    UPDATE_TIME     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    DEL_FLAG        SMALLINT     DEFAULT 0
);
COMMENT ON TABLE ONT_NOTIFICATION_LOG IS '通知记录';
COMMENT ON COLUMN ONT_NOTIFICATION_LOG.STATUS IS 'PENDING/SENT/FAILED';
CREATE INDEX IDX_ONT_NLOG_CID ON ONT_NOTIFICATION_LOG(CONFIG_ID);

-- 12. 函数定义
CREATE TABLE IF NOT EXISTS ONT_FUNCTION (
    ID              BIGINT       PRIMARY KEY,
    ONTOLOGY_ID     BIGINT       NOT NULL,
    NAME            VARCHAR(100) NOT NULL,
    CODE            VARCHAR(100) NOT NULL,
    LANG            VARCHAR(10)  NOT NULL,
    FUNC_TYPE       VARCHAR(20)  NOT NULL,
    BODY            TEXT,
    DESCRIPTION     TEXT,
    ENABLED         BOOLEAN      DEFAULT TRUE,
    NEEDS_APPROVAL  BOOLEAN      DEFAULT FALSE,
    CREATOR_ID      BIGINT,
    CREATE_BY       VARCHAR(50),
    CREATE_TIME     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATER_ID      BIGINT,
    UPDATE_BY       VARCHAR(50),
    UPDATE_TIME     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    DEL_FLAG        SMALLINT     DEFAULT 0
);
COMMENT ON TABLE ONT_FUNCTION IS '函数定义';
COMMENT ON COLUMN ONT_FUNCTION.LANG IS 'TYPESCRIPT/PYTHON';
COMMENT ON COLUMN ONT_FUNCTION.FUNC_TYPE IS 'PRE_HOOK/POST_HOOK/TRANSFORM/VALIDATOR';
CREATE INDEX IDX_ONT_FUNC_OID ON ONT_FUNCTION(ONTOLOGY_ID);

-- 13. 函数执行记录
CREATE TABLE IF NOT EXISTS ONT_FUNCTION_EXECUTION (
    ID              BIGINT       PRIMARY KEY,
    FUNCTION_ID     BIGINT       NOT NULL,
    EXECUTION_ID    BIGINT,
    INPUT_DATA      JSONB,
    OUTPUT_DATA     JSONB,
    STATUS          VARCHAR(20)  DEFAULT 'PENDING_APPROVAL',
    APPROVAL_REASON TEXT,
    ERROR_MESSAGE   TEXT,
    DURATION_MS     BIGINT,
    CREATOR_ID      BIGINT,
    CREATE_BY       VARCHAR(50),
    CREATE_TIME     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATER_ID      BIGINT,
    UPDATE_BY       VARCHAR(50),
    UPDATE_TIME     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    DEL_FLAG        SMALLINT     DEFAULT 0
);
COMMENT ON TABLE ONT_FUNCTION_EXECUTION IS '函数执行记录';
COMMENT ON COLUMN ONT_FUNCTION_EXECUTION.STATUS IS 'PENDING_APPROVAL/APPROVED/REJECTED/SUCCESS/FAILED';
CREATE INDEX IDX_ONT_FEXEC_FID ON ONT_FUNCTION_EXECUTION(FUNCTION_ID);

-- 14. 关系关联表绑定
CREATE TABLE IF NOT EXISTS ONT_RELATION_TABLE (
    ID              BIGINT       PRIMARY KEY,
    RELATION_ID     BIGINT       NOT NULL,
    DATASOURCE_ID   BIGINT       NOT NULL,
    DATABASE_NAME   VARCHAR(100),
    TABLE_NAME      VARCHAR(100) NOT NULL,
    SCHEMA_NAME     VARCHAR(100),
    COLUMN_NAMES    TEXT,
    CREATOR_ID      BIGINT,
    CREATE_BY       VARCHAR(50),
    CREATE_TIME     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATER_ID      BIGINT,
    UPDATE_BY       VARCHAR(50),
    UPDATE_TIME     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    DEL_FLAG        SMALLINT     DEFAULT 0
);
COMMENT ON TABLE ONT_RELATION_TABLE IS '关系关联表绑定';
COMMENT ON COLUMN ONT_RELATION_TABLE.COLUMN_NAMES IS '已选物理字段名, JSON数组';
CREATE INDEX IDX_ONT_RTABLE_RID ON ONT_RELATION_TABLE(RELATION_ID);
