-- =============================================
-- 数据绑定/决策/Webhook/接收工程 新增表结构 (PostgreSQL)
-- 涉及模块:
--   datamaster-ontology-core : ONT_WEBHOOK / ONT_WEBHOOK_LOG / ONT_DECISION / ONT_DECISION_EXECUTION
--   datamaster-ingestion     : INGESTION_LOG
-- 执行前请备份数据库
-- 注意: 必须用应用连接账号执行 (dev 为 datamaster),
--       否则表 owner 错误会导致应用报 permission denied
-- 本文件为 UTF-8 编码, 执行前必须保证客户端按 UTF-8 读取:
--   psql    : 先执行 \encoding UTF8 (或 PGCLIENTENCODING=UTF8)
--   Navicat: 查询窗口编码选择 65001 (UTF-8)
-- =============================================
SET client_encoding = 'UTF8';

-- 1. Webhook 配置
CREATE TABLE IF NOT EXISTS ONT_WEBHOOK (
    ID               BIGINT       PRIMARY KEY,
    NAME             VARCHAR(100) NOT NULL,
    ONTOLOGY_ID      BIGINT,
    ACTION_ID        BIGINT,
    URL              VARCHAR(500) NOT NULL,
    METHOD           VARCHAR(10)  DEFAULT 'POST',
    HEADERS          TEXT,
    PAYLOAD_TEMPLATE TEXT,
    SECRET           VARCHAR(200),
    ENABLED          BOOLEAN      DEFAULT TRUE,
    MAX_RETRY        INT          DEFAULT 0,
    DESCRIPTION      TEXT,
    CREATOR_ID       BIGINT,
    CREATE_BY        VARCHAR(50),
    CREATE_TIME      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATER_ID       BIGINT,
    UPDATE_BY        VARCHAR(50),
    UPDATE_TIME      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    DEL_FLAG         SMALLINT     DEFAULT 0
);
COMMENT ON TABLE ONT_WEBHOOK IS 'Webhook配置：动作/决策执行后回写源系统';
COMMENT ON COLUMN ONT_WEBHOOK.METHOD IS 'POST/PUT，默认 POST';
COMMENT ON COLUMN ONT_WEBHOOK.HEADERS IS '请求头 JSON';
COMMENT ON COLUMN ONT_WEBHOOK.PAYLOAD_TEMPLATE IS '请求体模板 JSON 字符串';
COMMENT ON COLUMN ONT_WEBHOOK.SECRET IS '回调密钥';
COMMENT ON COLUMN ONT_WEBHOOK.ENABLED IS '是否启用';
COMMENT ON COLUMN ONT_WEBHOOK.MAX_RETRY IS '失败最大重试次数，0 不重试';
CREATE INDEX IDX_ONT_WEBHOOK_OID ON ONT_WEBHOOK(ONTOLOGY_ID);
CREATE INDEX IDX_ONT_WEBHOOK_AID ON ONT_WEBHOOK(ACTION_ID);

-- 2. Webhook 回调日志
CREATE TABLE IF NOT EXISTS ONT_WEBHOOK_LOG (
    ID                  BIGINT       PRIMARY KEY,
    WEBHOOK_ID          BIGINT       NOT NULL,
    WEBHOOK_NAME        VARCHAR(100),
    EXECUTION_TYPE      VARCHAR(20)  NOT NULL,
    ACTION_EXECUTION_ID BIGINT,
    DECISION_EXECUTION_ID BIGINT,
    ONTOLOGY_ID         BIGINT,
    PAYLOAD             TEXT,
    STATUS              VARCHAR(20)  DEFAULT 'PENDING',
    HTTP_STATUS         INT,
    RESPONSE_BODY       TEXT,
    ERROR_MESSAGE       TEXT,
    RETRY_COUNT         INT          DEFAULT 0,
    CREATOR_ID          BIGINT,
    CREATE_BY           VARCHAR(50),
    CREATE_TIME         TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATER_ID          BIGINT,
    UPDATE_BY           VARCHAR(50),
    UPDATE_TIME         TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    DEL_FLAG            SMALLINT     DEFAULT 0
);
COMMENT ON TABLE ONT_WEBHOOK_LOG IS 'Webhook回调日志';
COMMENT ON COLUMN ONT_WEBHOOK_LOG.EXECUTION_TYPE IS 'ACTION/DECISION';
COMMENT ON COLUMN ONT_WEBHOOK_LOG.STATUS IS 'SUCCESS/FAILED/PENDING';
CREATE INDEX IDX_ONT_WEBHOOK_LOG_WID ON ONT_WEBHOOK_LOG(WEBHOOK_ID);
CREATE INDEX IDX_ONT_WEBHOOK_LOG_AEXEC ON ONT_WEBHOOK_LOG(ACTION_EXECUTION_ID);

-- 3. 决策定义
CREATE TABLE IF NOT EXISTS ONT_DECISION (
    ID              BIGINT       PRIMARY KEY,
    ONTOLOGY_ID     BIGINT       NOT NULL,
    NAME            VARCHAR(100) NOT NULL,
    ACTION_ID       BIGINT       NOT NULL,
    TRIGGER_TYPE    VARCHAR(20)  DEFAULT 'MANUAL',
    TRIGGER_REF     VARCHAR(200),
    ENABLED         BOOLEAN      DEFAULT TRUE,
    DESCRIPTION     TEXT,
    CREATOR_ID      BIGINT,
    CREATE_BY       VARCHAR(50),
    CREATE_TIME     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATER_ID      BIGINT,
    UPDATE_BY       VARCHAR(50),
    UPDATE_TIME     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    DEL_FLAG        SMALLINT     DEFAULT 0
);
COMMENT ON TABLE ONT_DECISION IS '决策定义：绑定动作 + 可选数据到达触发';
COMMENT ON COLUMN ONT_DECISION.ACTION_ID IS '绑定动作ID：决策执行触发该动作（复用动作执行引擎）';
COMMENT ON COLUMN ONT_DECISION.TRIGGER_TYPE IS 'MANUAL 手动 / DATA_ARRIVAL 数据到达触发';
COMMENT ON COLUMN ONT_DECISION.TRIGGER_REF IS '数据到达触发引用（接收工程写入数据集标识）';
COMMENT ON COLUMN ONT_DECISION.ENABLED IS '是否启用（数据到达触发仅启用时生效）';
CREATE INDEX IDX_ONT_DECISION_OID ON ONT_DECISION(ONTOLOGY_ID);
CREATE INDEX IDX_ONT_DECISION_AID ON ONT_DECISION(ACTION_ID);

-- 4. 决策执行记录
CREATE TABLE IF NOT EXISTS ONT_DECISION_EXECUTION (
    ID                  BIGINT       PRIMARY KEY,
    DECISION_ID         BIGINT       NOT NULL,
    ONTOLOGY_ID         BIGINT,
    EXECUTOR_ID         BIGINT,
    SPACE_ID            BIGINT,
    SPACE_CODE          VARCHAR(50),
    INPUT_PARAMS        JSONB,
    ACTION_EXECUTION_ID BIGINT,
    GENERATED_SQL       TEXT,
    PREVIEW_RESULT      JSONB,
    BEFORE_DATA         JSONB,
    AFTER_DATA          JSONB,
    STATUS              VARCHAR(20)  DEFAULT 'PENDING_APPROVAL',
    APPROVAL_REASON     TEXT,
    APPROVER_ID         BIGINT,
    APPROVE_TIME        TIMESTAMP,
    EXECUTE_TIME        TIMESTAMP,
    ROLLBACK_AFTER_DATA JSONB,
    ERROR_MESSAGE       TEXT,
    CREATOR_ID          BIGINT,
    CREATE_BY           VARCHAR(50),
    CREATE_TIME         TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATER_ID          BIGINT,
    UPDATE_BY           VARCHAR(50),
    UPDATE_TIME         TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    DEL_FLAG            SMALLINT     DEFAULT 0
);
COMMENT ON TABLE ONT_DECISION_EXECUTION IS '决策执行记录：委托绑定动作执行';
COMMENT ON COLUMN ONT_DECISION_EXECUTION.ACTION_EXECUTION_ID IS '委托动作执行记录ID';
COMMENT ON COLUMN ONT_DECISION_EXECUTION.STATUS IS 'PENDING_APPROVAL/APPROVED/REJECTED/EXECUTED/FAILED/ROLLED_BACK';
CREATE INDEX IDX_ONT_DEXEC_DID ON ONT_DECISION_EXECUTION(DECISION_ID);
CREATE INDEX IDX_ONT_DEXEC_STATUS ON ONT_DECISION_EXECUTION(STATUS);

-- 5. 数据接收处理日志
CREATE TABLE IF NOT EXISTS INGESTION_LOG (
    ID            BIGINT       PRIMARY KEY,
    TOPIC         VARCHAR(200) NOT NULL,
    PARTITION     INT,
    MSG_OFFSET    BIGINT,
    TARGET_TABLE  VARCHAR(200),
    STATUS        VARCHAR(20)  NOT NULL,
    CONFLICT_ACTION VARCHAR(20),
    KEY_VALUE     TEXT,
    MESSAGE_BODY  TEXT,
    MESSAGE       TEXT,
    CREATOR_ID    BIGINT,
    CREATE_BY     VARCHAR(50),
    CREATE_TIME   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATER_ID    BIGINT,
    UPDATE_BY     VARCHAR(50),
    UPDATE_TIME   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    DEL_FLAG      SMALLINT     DEFAULT 0
);
COMMENT ON TABLE INGESTION_LOG IS '数据接收处理日志（Kafka消费->冲突检查->写入数仓）';
COMMENT ON COLUMN INGESTION_LOG.STATUS IS 'SUCCESS/CONFLICT_SKIP/CONFLICT_ERROR/FAILED';
COMMENT ON COLUMN INGESTION_LOG.CONFLICT_ACTION IS 'INSERT/UPSERT/SKIP/ERROR';
CREATE INDEX IDX_ING_LOG_TOPIC ON INGESTION_LOG(TOPIC);
CREATE INDEX IDX_ING_LOG_STATUS ON INGESTION_LOG(STATUS);