<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>datamaster-service</artifactId>
        <groupId>com.datamaster</groupId>
        <version>${dataMaster.version}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>datamaster-service-core</artifactId>
    <description>
        datamaster-service-core 数据服务核心模块
    </description>
    <dependencies>
        <!-- 服务接口模块 -->
        <dependency>
            <groupId>com.datamaster</groupId>
            <artifactId>datamaster-service-interface</artifactId>
            <version>${dataMaster.version}</version>
        </dependency>
        <!-- 通用工具-->
        <dependency>
            <groupId>com.datamaster</groupId>
            <artifactId>datamaster-common-common</artifactId>
        </dependency>
        <!-- 核心模块 config-->
        <dependency>
            <groupId>com.datamaster</groupId>
            <artifactId>datamaster-common-config</artifactId>
            <version>${dataMaster.version}</version>
        </dependency>
        <!-- 系統模块 websocket-->
        <dependency>
            <groupId>com.datamaster</groupId>
            <artifactId>datamaster-common-websocket</artifactId>
            <version>${dataMaster.version}</version>
        </dependency>
        <!-- 系统模块 datasource -->
        <dependency>
            <groupId>com.datamaster</groupId>
            <artifactId>datamaster-common-datasource</artifactId>
            <version>${dataMaster.version}</version>
        </dependency>
        <!-- 系统模块 mybatis -->
        <dependency>
            <groupId>com.datamaster</groupId>
            <artifactId>datamaster-common-mybatis</artifactId>
            <version>${dataMaster.version}</version>
        </dependency>
        <!-- 系统模块 redis -->
        <dependency>
            <groupId>com.datamaster</groupId>
            <artifactId>datamaster-common-base</artifactId>
            <version>${dataMaster.version}</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.datamaster</groupId>
            <artifactId>datamaster-api-ds</artifactId>
            <version>${dataMaster.version}</version>
        </dependency>
        <!-- 数据资产接口 -->
        <dependency>
            <groupId>com.datamaster</groupId>
            <artifactId>datamaster-assets-interface</artifactId>
            <version>${dataMaster.version}</version>
        </dependency>
        <!-- 脱敏公共能力 -->
        <dependency>
            <groupId>com.datamaster</groupId>
            <artifactId>datamaster-governance-core</artifactId>
            <version>${dataMaster.version}</version>
        </dependency>
        <dependency>
            <groupId>com.datamaster</groupId>
            <artifactId>datamaster-system</artifactId>
            <version>${dataMaster.version}</version>
        </dependency>
        <!-- 公共数据源管理 -->
        <dependency>
            <groupId>com.datamaster</groupId>
            <artifactId>datamaster-common-datasource-mgmt</artifactId>
        </dependency>
    </dependencies>
</project>
