DATAMASTER:
  # 名称
  name: DATAMASTER
  # 版本
  version: 1.4.0
  copyrightYear: 2024
  # 文件路径 示例（ Windows配置D:/DATAMASTER/uploadPath，Linux配置 /home/DATAMASTER/uploadPath） -- 需要和 file 模块保持一致
  profile: ${user.dir}/upload/ # 存储路径
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8083
  port: 8087
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    tech.qiantong: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10
    #万能密码 配置为空则不生效
    universalPassword: gfh78h23789#$gfdy845

# Spring配置
spring:
  main:
    allow-circular-references: true
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: dev  # 默认激活的环境，可以在启动时覆盖
  config:
    import:
      - "application-${spring.profiles.active}.yml"
      - "classpath:application-auth-${spring.profiles.active}.yml"
      - "classpath:application-file-${spring.profiles.active}.yml"
      - "classpath:application-system-${spring.profiles.active}.yml"
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 3000MB
      # 设置总上传的文件大小
      max-request-size: 3000MB

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌自定义标识
  rpHeader: token
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 600

# MyBatis Plus配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: tech.qiantong.**.dataobject,tech.qiantong.**.dataobject.assetchild, tech.qiantong.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
  global-config:
    # 关闭 MyBatis-Plus 的 Banner
    banner: false
    db-config:
      # 主键类型 AUTO 自增 NONE 空 INPUT 用户输入 ASSIGN_ID 雪花 ASSIGN_UUID 唯一 UUID
      idType: AUTO
      # 全局逻辑删除字段名
      logic-delete-field: delFlag
      # 逻辑已删除值（默认为1）
      logic-delete-value: 1
      # 逻辑未删除值（默认为0）
      logic-not-delete-value: 0
      # 字段验证策略之 insert,在 insert 的时候的字段验证策略 IGNORED 忽略 NOT_NULL 非NULL NOT_EMPTY 非空 DEFAULT 默认 NEVER 不加入 SQL
      insertStrategy: NOT_NULL
      # 字段验证策略之 update,在 update 的时候的字段验证策略
      updateStrategy: NOT_NULL
      # 字段验证策略之 select,在 select 的时候的字段验证策略既 wrapper 根据内部 entity 生成的 where 条件
      where-strategy: NOT_NULL

mybatis-plus-join:
  # 是否打印 mybatis plus join banner，默认true
  banner: false
  # 全局启用副表逻辑删除，默认true。关闭后关联查询不会加副表逻辑删除
  sub-table-logic: true
  # 拦截器MappedStatement缓存，默认 true
  ms-cache: true
  # 表别名(默认 t)
  table-alias: t
  # 副表逻辑删除条件的位置，支持 WHERE、ON，默认 ON
  logic-del-type: on

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*


#ID生成器使用 为以后分布式不重复ID做应用
#工作机器ID(0~31)
id.workerId: 1
#数据中心ID(0~31)
id.datacenterId: 1
